### ISSUE TITLE
Pelican driver needs to read multiple thermostats

### ISSUE THREAD

**Issue by gtfierro** [SoftwareDefinedBuildings/XBOS#46]
Right now it seems that this is not the case? A Pelican site can have multiple thermostats; the driver needs to discover those and report them as it would with a single thermostat. Step one will be removing the thermostat name from the parameters file

Including @jhkolb here to see if there's any major issues that will get in the way of this change

**Comment by jhkolb** [comment]
I can't think of any major issues. We could even have one of the work studies do it as a project, unless this is time-sensitive.

How do you propose doing the discovery? It's been a while since I've looked at the Pelican API. Can we just use their `selection` query parameter with an empty list of tags, or something similar, to list out all of the thermostats that are under a single Pelican "domain" ?

**Comment by jhkolb** [comment]
See pull request 17 on the `bw2-contrib` repo.
